version: "3"

services:
    nginx:
        image: nginx
        volumes:
            - "./config/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "./config/etc/ssl:/etc/ssl"
            - "./config/web:/var/www/html"
            - "./config/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
            - "./log:/var/log/nginx"
        ports:
            - "8080:80"
            - "8443:443"
        environment:
            - NGINX_HOST=domain.com
            - NGINX_PORT=80
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
    jenkins:
        image: jenkins/jenkins:lts
        ports:
          - "50000:50000"
          - "8888:8080"
        environment:
          - JENKINS_SLAVE_AGENT_PORT=50000
          - JENKINS_OPTS=--prefix=/jenkins
        volumes:
          - ./jenkins:/var/jenkins_home
        links:
          - nginx